const API = 'http://localhost:8000/api';
const token = () => localStorage.getItem('token');
async function api(path, options={}){ const res=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{}),...(options.headers||{})}}); const data=await res.json().catch(()=>null); if(!res.ok) throw new Error(data?.error||'Erro'); return data; }
function statusLabel(s){ return ({READ:'Lido',READING:'Lendo',NEXT_READ:'Próxima leitura',WANT_FUTURE:'Desejo ter futuramente',DUSTY:'Pegando poeira',GIFT_ACCEPTED:'Aceito presente',ABANDONED:'Abandonei',REREADING:'Relendo',WANT_SPECIAL_EDITION:'Quero edição especial'})[s]||s; }
async function register(){ try{ const body={name:name.value,username:username.value,email:email.value,password:password.value,bio:bio.value}; const r=await api('/auth/register',{method:'POST',body:JSON.stringify(body)}); localStorage.setItem('token',r.token); location.href='perfil.html'; }catch(e){msg.textContent=e.message;} }
async function login(){ try{ const r=await api('/auth/login',{method:'POST',body:JSON.stringify({login:login.value,password:password.value})}); localStorage.setItem('token',r.token); location.href='perfil.html'; }catch(e){msg.textContent=e.message;} }
async function loadBooks(){ const q=document.getElementById('q')?.value||''; const data=await api('/books?q='+encodeURIComponent(q)); books.innerHTML=data.map(b=>`<article class="card"><h3>${b.title}</h3><p class="muted">${b.author}</p><span class="badge">${b.genre}</span><p>${b.description||''}</p><select id="s${b.id}"><option value="WANT_FUTURE">Desejo ter futuramente</option><option value="GIFT_ACCEPTED">Aceito presente</option><option value="NEXT_READ">Próxima leitura</option><option value="READING">Lendo</option><option value="READ">Lido</option><option value="DUSTY">Pegando poeira</option></select><input id="n${b.id}" placeholder="Comentário pessoal"><button onclick="addBook(${b.id})">Adicionar ao perfil</button></article>`).join(''); }
async function addBook(id){ await api('/books/'+id+'/add',{method:'POST',body:JSON.stringify({status:document.getElementById('s'+id).value,notes:document.getElementById('n'+id).value})}); alert('Livro adicionado ao perfil'); }
async function loadMyProfile(){ const me=await api('/auth/me'); const p=await api('/users/'+me.username); renderProfile(p); }
function renderProfile(p){ profile.innerHTML=`<h1>${p.user.name}</h1><p>${p.user.username}</p><p>${p.user.bio||''}</p><p><b>${p.stats.total}</b> livros • <b>${p.stats.read}</b> lidos • <b>${p.stats.reading}</b> lendo • <b>${p.stats.next_read}</b> próxima leitura • <b>${p.stats.want_future}</b> desejo ter • <b>${p.stats.gift_accepted}</b> aceito presente</p>${p.favorite_categories.map(c=>`<span class="badge">${c.name}</span>`).join('')}`; profileBooks.innerHTML=p.books.map((b,i)=>`<article class="item"><b>${i+1}. ${b.title}</b><p class="muted">${b.author} • ${b.genre}</p><span class="badge">${statusLabel(b.status)}</span> ${b.favorite?'❤️':''}<p class="stars">${'★'.repeat(b.rating||0)}</p><p>${b.notes||''}</p></article>`).join(''); }
async function exploreUsers(){ const q=document.getElementById('q')?.value||''; const data=await api('/users?q='+encodeURIComponent(q)); users.innerHTML=data.map(u=>`<article class="card"><h3>${u.name}</h3><p>${u.username}</p><p>${u.bio||''}</p><p>${u.books_count} livros</p><button onclick="alert('Abra /api/users/${u.username.replace('@','')} ou implemente página pública dedicada')">Ver perfil</button><button onclick="follow(${u.id})">Seguir</button></article>`).join(''); }
async function follow(id){ await api('/follow/'+id,{method:'POST'}); alert('Agora você segue este usuário'); }
async function loadFeed(){ const data=await api('/feed'); feed.innerHTML=data.map(f=>`<article class="item"><b>${f.name} ${f.username}</b><p>${statusLabel(f.status)}: <b>${f.title}</b> — ${f.author}</p><span class="badge">${f.genre}</span><p>${f.notes||''}</p></article>`).join('')||'<p class="muted">Siga usuários para montar seu feed.</p>'; }
async function savePix(){ try{ const r=await api('/pix/key',{method:'POST',body:JSON.stringify({key_type:key_type.value,pix_key:pix_key.value,holder_name:holder_name.value})}); msg.textContent=JSON.stringify(r,null,2);}catch(e){msg.textContent=e.message;} }
