<?php
use App\Core\Router;
use App\Controllers\{AuthController,UserController,BookController,FollowController,FeedController,PixController};
$r=new Router();
$r->add('POST','/auth/register',fn()=>AuthController::register());
$r->add('POST','/auth/login',fn()=>AuthController::login());
$r->add('GET','/auth/me',fn()=>AuthController::me());
$r->add('GET','/users',fn()=>UserController::index());
$r->add('GET','/users/{username}',fn($p)=>UserController::show($p));
$r->add('PUT','/users/profile',fn()=>UserController::update());
$r->add('POST','/users/{id}/like',fn($p)=>UserController::like($p));
$r->add('POST','/follow/{id}',fn($p)=>FollowController::follow($p));
$r->add('DELETE','/follow/{id}',fn($p)=>FollowController::unfollow($p));
$r->add('GET','/feed',fn()=>FeedController::index());
$r->add('GET','/books',fn()=>BookController::catalog());
$r->add('POST','/books',fn()=>BookController::create());
$r->add('GET','/books/{id}',fn($p)=>BookController::show($p));
$r->add('GET','/books/categories',fn()=>BookController::genres());
$r->add('GET','/books/authors',fn()=>BookController::authors());
$r->add('POST','/books/{bookId}/add',fn($p)=>BookController::addToLibrary($p));
$r->add('PUT','/user-books/{bookId}',fn($p)=>BookController::updateUserBook($p));
$r->add('DELETE','/user-books/{bookId}',fn($p)=>BookController::remove($p));
$r->add('PUT','/user-books/reorder',fn()=>BookController::reorder());
$r->add('POST','/books/{bookId}/comments',fn($p)=>BookController::comment($p));
$r->add('GET','/pix/key',fn()=>PixController::myKey());
$r->add('POST','/pix/key',fn()=>PixController::saveKey());
$r->add('POST','/pix/gift/{bookId}',fn($p)=>PixController::gift($p));
$r->dispatch();
