const API='';
function token(){return localStorage.getItem('token')||''}
async function api(path,opts={}){opts.headers={...(opts.headers||{}),'Content-Type':'application/json'}; if(token()) opts.headers.Authorization='Bearer '+token(); const r=await fetch(API+path,opts); const j=await r.json().catch(()=>({})); if(!r.ok) throw j; return j;}
async function login(){try{const j=await api('/login.php',{method:'POST',body:JSON.stringify({login:document.getElementById('login').value,password:document.getElementById('password').value})});localStorage.setItem('token',j.token);out.textContent='Logado como @'+j.user.username}catch(e){out.textContent=JSON.stringify(e,null,2)}}
async function register(){try{const j=await api('/register.php',{method:'POST',body:JSON.stringify({name:name.value,username:username.value,email:email.value,password:password.value,bio:bio.value})});localStorage.setItem('token',j.token);out.textContent='Cadastro realizado: @'+j.user.username}catch(e){out.textContent=JSON.stringify(e,null,2)}}
async function loadBooks(){const el=document.getElementById('books'); if(!el)return; const j=await api('/books.php'); el.innerHTML=j.books.map(b=>`<div class="card"><b>${b.title}</b><br>${b.author}<br><span class="badge">${b.genre}</span><br><button onclick="addBook(${b.id},'READING')">Lendo</button><button onclick="addBook(${b.id},'READ')">Lido</button><button onclick="addBook(${b.id},'GIFT_ACCEPTED')">Aceito presente</button></div>`).join('')}
async function addBook(book_id,status){alert(JSON.stringify(await api('/add-book.php',{method:'POST',body:JSON.stringify({book_id,status})}),null,2))}
async function searchUsers(){const q=document.getElementById('searchUsers')?.value||''; const el=document.getElementById('users'); if(!el)return; const j=await api('/users.php?q='+encodeURIComponent(q)); el.innerHTML=j.users.map(u=>`<div class="card"><b>${u.name}</b> @${u.username}<p>${u.bio||''}</p><span class="badge">${u.total_books} livros</span></div>`).join('')}
document.getElementById('searchUsers')?.addEventListener('input',searchUsers); loadBooks(); searchUsers();
