<?php
require_once __DIR__ . '/db.php';
$sql = <<<SQL
CREATE TABLE IF NOT EXISTS users (
 id SERIAL PRIMARY KEY, name VARCHAR(120) NOT NULL, username VARCHAR(60) UNIQUE NOT NULL, email VARCHAR(160) UNIQUE NOT NULL, password_hash TEXT NOT NULL, bio TEXT, avatar TEXT, pix_key_type VARCHAR(30), pix_key TEXT, created_at TIMESTAMP DEFAULT now(), updated_at TIMESTAMP DEFAULT now()
);
CREATE TABLE IF NOT EXISTS authors (id SERIAL PRIMARY KEY, name VARCHAR(160) UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS genres (id SERIAL PRIMARY KEY, name VARCHAR(160) UNIQUE NOT NULL, slug VARCHAR(160) UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS books (id SERIAL PRIMARY KEY, title VARCHAR(220) NOT NULL, original_title VARCHAR(220), author_id INT REFERENCES authors(id), genre_id INT REFERENCES genres(id), description TEXT, created_at TIMESTAMP DEFAULT now(), UNIQUE(title, author_id));
CREATE TABLE IF NOT EXISTS user_books (id SERIAL PRIMARY KEY, user_id INT REFERENCES users(id) ON DELETE CASCADE, book_id INT REFERENCES books(id) ON DELETE CASCADE, status VARCHAR(40) NOT NULL DEFAULT 'WANT_FUTURE', rating INT, notes TEXT, favorite BOOLEAN DEFAULT FALSE, display_order INT DEFAULT 0, created_at TIMESTAMP DEFAULT now(), updated_at TIMESTAMP DEFAULT now(), UNIQUE(user_id,book_id));
CREATE TABLE IF NOT EXISTS follows (follower_id INT REFERENCES users(id) ON DELETE CASCADE, following_id INT REFERENCES users(id) ON DELETE CASCADE, created_at TIMESTAMP DEFAULT now(), PRIMARY KEY(follower_id, following_id));
CREATE TABLE IF NOT EXISTS book_comments (id SERIAL PRIMARY KEY, user_id INT REFERENCES users(id) ON DELETE CASCADE, book_id INT REFERENCES books(id) ON DELETE CASCADE, body TEXT NOT NULL, created_at TIMESTAMP DEFAULT now());
CREATE TABLE IF NOT EXISTS profile_likes (user_id INT REFERENCES users(id) ON DELETE CASCADE, liked_user_id INT REFERENCES users(id) ON DELETE CASCADE, created_at TIMESTAMP DEFAULT now(), PRIMARY KEY(user_id, liked_user_id));
CREATE TABLE IF NOT EXISTS gifts (id SERIAL PRIMARY KEY, from_user_id INT REFERENCES users(id), to_user_id INT REFERENCES users(id), book_id INT REFERENCES books(id), amount NUMERIC(10,2), message TEXT, status VARCHAR(30) DEFAULT 'PENDING', created_at TIMESTAMP DEFAULT now());
SQL;
db()->exec($sql);
function slug($s){ $s=iconv('UTF-8','ASCII//TRANSLIT',$s); $s=strtolower(preg_replace('/[^a-zA-Z0-9]+/','-', $s)); return trim($s,'-'); }
$books = [
['Literatura Psicológica','Fiódor Dostoiévski','Crime e Castigo'],['Literatura Psicológica','Fiódor Dostoiévski','O Idiota'],['Literatura Psicológica','Fiódor Dostoiévski','Memórias do Subsolo'],['Literatura Psicológica','Fiódor Dostoiévski','Noites Brancas'],['Literatura Psicológica','Fiódor Dostoiévski','O Jogador'],['Literatura Psicológica','Sylvia Plath','A Redoma de Vidro'],['Literatura Psicológica','Osamu Dazai','Declínio de um Homem (No Longer Human)'],['Literatura Psicológica','Anton Tchékhov','Pavilhão nº 6'],['Literatura Psicológica','John Williams','Stoner'],
['Literatura Filosófica e Existencialista','Fiódor Dostoiévski','Os Irmãos Karamázov'],['Literatura Filosófica e Existencialista','Franz Kafka','O Processo'],['Literatura Filosófica e Existencialista','Franz Kafka','O Castelo'],['Literatura Filosófica e Existencialista','Franz Kafka','A Metamorfose'],['Literatura Filosófica e Existencialista','Franz Kafka','Carta ao Pai'],['Literatura Filosófica e Existencialista','Franz Kafka','América'],['Literatura Filosófica e Existencialista','Albert Camus','O Estrangeiro'],['Literatura Filosófica e Existencialista','Albert Camus','O Mal-Entendido'],['Literatura Filosófica e Existencialista','Liev Tolstói','Ressurreição'],['Literatura Filosófica e Existencialista','Liev Tolstói','A Morte de Ivan Ilitch'],['Literatura Filosófica e Existencialista','Cormac McCarthy','A Estrada (The Road)'],
['Literatura Social e Realista','Fiódor Dostoiévski','Gente Pobre'],['Literatura Social e Realista','Nikolai Gógol','O Capote'],['Literatura Social e Realista','Aleksandr Kuprin','Yama: O Fosso'],['Literatura Social e Realista','Graciliano Ramos','Vidas Secas'],['Literatura Social e Realista','Ivan Turguêniev','Mumu'],['Literatura Social e Realista','James Baldwin',"O Quarto de Giovanni (Giovanni's Room)"],
['Literatura Familiar','Liev Tolstói','Anna Kariênina'],['Literatura Familiar','Ivan Turguêniev','Pais e Filhos'],['Literatura Histórica','Liev Tolstói','Guerra e Paz'],['Literatura Histórica','Kristin Hannah','O Rouxinol (The Nightingale)'],['Literatura Histórica','Kristin Hannah','Os Quatro Ventos (The Four Winds)'],['Literatura Gótica e Horror Sobrenatural','Nikolai Gógol','Viy'],['Sátira e Fantástico','Nikolai Gógol','Almas Mortas'],['Romance Sentimental','Nikolai Karamzin','Pobre Liza'],['Teatro Clássico','William Shakespeare','Hamlet'],['Poesia Épica','John Milton','Paraíso Perdido'],['Distopia','George Orwell','1984'],['Distopia','George Orwell','A Revolução dos Bichos'],['Distopia','Aldous Huxley','Admirável Mundo Novo'],['Filosofia','Jean-Jacques Rousseau','Confissões'],['Filosofia','Nicolau Maquiavel','O Príncipe'],['Estratégia Militar','Sun Tzu','A Arte da Guerra'],['Psicologia, Persuasão e Comportamento Humano','Robert Greene','As 48 Leis do Poder'],['Psicologia, Persuasão e Comportamento Humano','Robert Greene','As Leis da Natureza Humana'],['Psicologia, Persuasão e Comportamento Humano','Jack Schafer e Marvin Karlins','Manual de Persuasão do FBI'],['Psicologia, Persuasão e Comportamento Humano','Joe Navarro','O Que Todo Corpo Fala'],['Romance Policial (True Crime)','Ilana Casoy','O Quinto Mandamento (caso Elize Matsunaga)'],['Fantasia Épica','J. K. Rowling','Harry Potter (coleção)'],['Fantasia Épica','George R. R. Martin','As Crônicas de Gelo e Fogo (coleção)']
];
foreach($books as [$genre,$author,$title]){
 $g=db()->prepare('INSERT INTO genres(name,slug) VALUES(?,?) ON CONFLICT(name) DO UPDATE SET name=EXCLUDED.name RETURNING id'); $g->execute([$genre,slug($genre)]); $gid=$g->fetch()['id'];
 $a=db()->prepare('INSERT INTO authors(name) VALUES(?) ON CONFLICT(name) DO UPDATE SET name=EXCLUDED.name RETURNING id'); $a->execute([$author]); $aid=$a->fetch()['id'];
 $b=db()->prepare('INSERT INTO books(title,author_id,genre_id) VALUES(?,?,?) ON CONFLICT(title,author_id) DO UPDATE SET genre_id=EXCLUDED.genre_id'); $b->execute([$title,$aid,$gid]);
}
if (php_sapi_name() !== 'cli') json_response(['ok'=>true,'message'=>'Migration e seed executados.']);
echo "Migration e seed executados.\n";
