<?php
namespace App\Controllers;
use App\Core\{Database,Request,Response}; use App\Middlewares\AuthMiddleware;
final class UserController {
  private static function stats(int $id): array { $pdo=Database::connection(); $rows=$pdo->prepare('SELECT status,COUNT(*) total FROM user_books WHERE user_id=? GROUP BY status'); $rows->execute([$id]); $s=['total'=>0,'read'=>0,'reading'=>0,'next_read'=>0,'want_future'=>0,'dusty'=>0,'gift_accepted'=>0,'favorites'=>0]; foreach($rows as $r){$s['total']+=(int)$r['total']; $s[strtolower($r['status'])]=(int)$r['total'];} $f=$pdo->prepare('SELECT COUNT(*) c FROM user_books WHERE user_id=? AND favorite=1'); $f->execute([$id]); $s['favorites']=(int)$f->fetch()['c']; return $s; }
  private static function books(int $id): array { $pdo=Database::connection(); $st=$pdo->prepare('SELECT ub.id user_book_id,ub.status,ub.rating,ub.notes,ub.favorite,ub.display_order,b.id,b.title,b.original_title,b.year,b.pages,b.cover,b.description,a.name author,g.name genre FROM user_books ub JOIN books b ON b.id=ub.book_id JOIN authors a ON a.id=b.author_id JOIN genres g ON g.id=b.genre_id WHERE ub.user_id=? ORDER BY ub.status,ub.display_order,b.title'); $st->execute([$id]); return $st->fetchAll(); }
  public static function index(): void { $q='%'.trim(Request::query()['q']??'').'%'; $pdo=Database::connection(); $st=$pdo->prepare('SELECT u.id,u.name,CONCAT("@",u.username) username,u.bio,u.avatar,COUNT(ub.id) books_count FROM users u LEFT JOIN user_books ub ON ub.user_id=u.id WHERE u.name LIKE ? OR u.username LIKE ? GROUP BY u.id ORDER BY books_count DESC,u.name LIMIT 50'); $st->execute([$q,$q]); Response::json($st->fetchAll()); }
  public static function show(array $p): void { $username=ltrim(strtolower($p['username']),'@'); $viewer=null; try{$viewer=AuthMiddleware::userId();}catch(\Throwable $e){} $pdo=Database::connection(); $st=$pdo->prepare('SELECT id,name,CONCAT("@",username) username,bio,avatar,created_at FROM users WHERE username=?'); $st->execute([$username]); $u=$st->fetch(); if(!$u) Response::json(['error'=>'Perfil não encontrado'],404); $fid=$u['id'];
    $follow=false; $liked=false; if($viewer){ $a=$pdo->prepare('SELECT id FROM follows WHERE follower_id=? AND followed_id=?');$a->execute([$viewer,$fid]);$follow=(bool)$a->fetch(); $l=$pdo->prepare('SELECT id FROM profile_likes WHERE user_id=? AND liked_user_id=?');$l->execute([$viewer,$fid]);$liked=(bool)$l->fetch(); }
    $cats=$pdo->prepare('SELECT g.name,COUNT(*) total FROM user_books ub JOIN books b ON b.id=ub.book_id JOIN genres g ON g.id=b.genre_id WHERE ub.user_id=? GROUP BY g.id ORDER BY total DESC LIMIT 5'); $cats->execute([$fid]);
    Response::json(['user'=>$u,'stats'=>self::stats((int)$fid),'favorite_categories'=>$cats->fetchAll(),'is_following'=>$follow,'liked'=>$liked,'books'=>self::books((int)$fid),'grouped_by_status'=>self::groupBy(self::books((int)$fid),'status'),'grouped_by_genre'=>self::groupBy(self::books((int)$fid),'genre')]); }
  private static function groupBy(array $rows,string $key): array { $out=[]; foreach($rows as $r){$out[$r[$key]][]=$r;} return $out; }
  public static function update(): void { $id=AuthMiddleware::userId(); $b=Request::body(); $pdo=Database::connection(); $st=$pdo->prepare('UPDATE users SET name=COALESCE(?,name), bio=?, avatar=?, updated_at=NOW() WHERE id=?'); $st->execute([$b['name']??null,$b['bio']??null,$b['avatar']??null,$id]); Response::json(['message'=>'Perfil atualizado']); }
  public static function like(array $p): void { $id=AuthMiddleware::userId(); $target=(int)$p['id']; $pdo=Database::connection(); if($id===$target) Response::json(['error'=>'Não é possível curtir o próprio perfil'],422); $st=$pdo->prepare('INSERT IGNORE INTO profile_likes(user_id,liked_user_id,created_at) VALUES(?,?,NOW())'); $st->execute([$id,$target]); Response::json(['message'=>'Perfil curtido']); }
}
